In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [3]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [5]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

# Here maligant means Cancer
# Here benign means Not cancer 

In [7]:
df = pd.DataFrame(np.c_[data.data,data.target],columns=[list(data.feature_names)+["target"]])
df.head(10)

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   
5       12.45        15.70          82.57     477.1         0.12780   
6       18.25        19.98         119.60    1040.0         0.09463   
7       13.71        20.83          90.20     577.9         0.11890   
8       13.00        21.82          87.50     519.8         0.12730   
9       12.46        24.04          83.97     475.9         0.11860   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760        0.30010             0.14710        0.2419   
1          0.07864        0.08690             0.07017        0.1812   
2          0.15990        0.19740             0.12790        0.2069   
3          0.28390        0.24140             0.10520        0.2597   
4          0.13280        0.19800             0.10430        0.1809   
5          0.17000        0.15780             0.08089        0.2087   
6          0.10900        0.11270             0.07400        0.1794   
7          0.16450        0.09366             0.05985        0.2196   
8          0.19320        0.18590             0.09353        0.2350   
9          0.23960        0.22730             0.08543        0.2030   

  mean fractal dimension  ... worst texture worst perimeter worst area  \
0                0.07871  ...         17.33          184.60     2019.0   
1                0.05667  ...         23.41          158.80     1956.0   
2                0.05999  ...         25.53          152.50     1709.0   
3                0.09744  ...         26.50           98.87      567.7   
4                0.05883  ...         16.67          152.20     1575.0   
5                0.07613  ...         23.75          103.40      741.6   
6                0.05742  ...         27.66          153.20     1606.0   
7                0.07451  ...         28.14          110.60      897.0   
8                0.07389  ...         30.73          106.20      739.3   
9                0.08243  ...         40.68           97.65      711.4   

  worst smoothness worst compactness worst concavity worst concave points  \
0           0.1622            0.6656          0.7119               0.2654   
1           0.1238            0.1866          0.2416               0.1860   
2           0.1444            0.4245          0.4504               0.2430   
3           0.2098            0.8663          0.6869               0.2575   
4           0.1374            0.2050          0.4000               0.1625   
5           0.1791            0.5249          0.5355               0.1741   
6           0.1442            0.2576          0.3784               0.1932   
7           0.1654            0.3682          0.2678               0.1556   
8           0.1703            0.5401          0.5390               0.2060   
9           0.1853            1.0580          1.1050               0.2210   

  worst symmetry worst fractal dimension target  
0         0.4601                 0.11890    0.0  
1         0.2750                 0.08902    0.0  
2         0.3613                 0.08758    0.0  
3         0.6638                 0.17300    0.0  
4         0.2364                 0.07678    0.0  
5         0.3985                 0.12440    0.0  
6         0.3063                 0.08368    0.0  
7         0.3196                 0.11510    0.0  
8         0.4378                 0.10720    0.0  
9         0.4366                 0.20750    0.0  

[10 rows x 31 columns]

In [8]:
df.shape

(569, 31)

In [9]:
X = df.iloc[: , 0:-1]
Y = df.iloc[: , -1]
Y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
564    0.0
565    0.0
566    0.0
567    0.0
568    1.0
Name: (target,), Length: 569, dtype: float64

In [10]:
X

mean radius mean texture mean perimeter mean area mean smoothness  \
0         17.99        10.38         122.80    1001.0         0.11840   
1         20.57        17.77         132.90    1326.0         0.08474   
2         19.69        21.25         130.00    1203.0         0.10960   
3         11.42        20.38          77.58     386.1         0.14250   
4         20.29        14.34         135.10    1297.0         0.10030   
..          ...          ...            ...       ...             ...   
564       21.56        22.39         142.00    1479.0         0.11100   
565       20.13        28.25         131.20    1261.0         0.09780   
566       16.60        28.08         108.30     858.1         0.08455   
567       20.60        29.33         140.10    1265.0         0.11780   
568        7.76        24.54          47.92     181.0         0.05263   

    mean compactness mean concavity mean concave points mean symmetry  \
0            0.27760        0.30010             0.14710        0.2419   
1            0.07864        0.08690             0.07017        0.1812   
2            0.15990        0.19740             0.12790        0.2069   
3            0.28390        0.24140             0.10520        0.2597   
4            0.13280        0.19800             0.10430        0.1809   
..               ...            ...                 ...           ...   
564          0.11590        0.24390             0.13890        0.1726   
565          0.10340        0.14400             0.09791        0.1752   
566          0.10230        0.09251             0.05302        0.1590   
567          0.27700        0.35140             0.15200        0.2397   
568          0.04362        0.00000             0.00000        0.1587   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
0                  0.07871  ...       25.380         17.33          184.60   
1                  0.05667  ...       24.990         23.41          158.80   
2                  0.05999  ...       23.570         25.53          152.50   
3                  0.09744  ...       14.910         26.50           98.87   
4                  0.05883  ...       22.540         16.67          152.20   
..                     ...  ...          ...           ...             ...   
564                0.05623  ...       25.450         26.40          166.10   
565                0.05533  ...       23.690         38.25          155.00   
566                0.05648  ...       18.980         34.12          126.70   
567                0.07016  ...       25.740         39.42          184.60   
568                0.05884  ...        9.456         30.37           59.16   

    worst area worst smoothness worst compactness worst concavity  \
0       2019.0          0.16220           0.66560          0.7119   
1       1956.0          0.12380           0.18660          0.2416   
2       1709.0          0.14440           0.42450          0.4504   
3        567.7          0.20980           0.86630          0.6869   
4       1575.0          0.13740           0.20500          0.4000   
..         ...              ...               ...             ...   
564     2027.0          0.14100           0.21130          0.4107   
565     1731.0          0.11660           0.19220          0.3215   
566     1124.0          0.11390           0.30940          0.3403   
567     1821.0          0.16500           0.86810          0.9387   
568      268.6          0.08996           0.06444          0.0000   

    worst concave points worst symmetry worst fractal dimension  
0                 0.2654         0.4601                 0.11890  
1                 0.1860         0.2750                 0.08902  
2                 0.2430         0.3613                 0.08758  
3                 0.2575         0.6638                 0.17300  
4                 0.1625         0.2364                 0.07678  
..                   ...            ...                     ...  
564               0.22

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 2020)

print("Shape of X_train", X_train.shape)
print("Shape of X_test", X_test.shape)
print("Shape of Y_train", Y_train.shape)
print("Shape of Y_test", Y_test.shape)

Shape of X_train (455, 30)
Shape of X_test (114, 30)
Shape of Y_train (455,)
Shape of Y_test (114,)


In [13]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
Classifier = DecisionTreeClassifier(criterion='gini')
Fitthedata = Classifier.fit(X_train.values,Y_train.values)
Fitthedata

DecisionTreeClassifier()

In [16]:
score = Classifier.score(X_test.values,Y_test.values)
score

0.956140350877193

In [17]:
Classifer_entropy = DecisionTreeClassifier(criterion="entropy")
Fitdata = Classifer_entropy.fit(X_train.values, Y_train.values)
Fitdata

DecisionTreeClassifier(criterion='entropy')

In [18]:
Score = Classifer_entropy.score(X_test.values,Y_test.values)

In [19]:
Score

0.9385964912280702

# Features Scalling

In [20]:
from sklearn.preprocessing import StandardScaler
Sc = StandardScaler()

In [21]:
Sc.fit(X_train.values)

StandardScaler()

In [22]:
X_train_sc = Sc.fit_transform(X_train.values)
X_test_sc = Sc.fit_transform(X_test.values)

In [23]:
Classifier_sc = DecisionTreeClassifier(criterion="gini")
fitdata = Classifier_sc.fit(X_train_sc,Y_train)
fitdata

DecisionTreeClassifier()

In [24]:
Scores = Classifier_sc.score(X_test_sc,Y_test)

In [25]:
Scores

0.956140350877193

# Now we will be able to predict the cancer

In [26]:
patient1 = [
    17.99,
    20.11,
    23.11,
    31,32,
    213.43,
    56.33,
    234.11,
    331.31,
    21.22,
    11.21,
    32.21,
    43.21,
    112.21,
    33.11,
    53.32,
    311.11,
    89.12,
    11.33,
    312.12,
    89.11,
    97.21,
    76.11,
    12.11,
    91.11,
    29.21,
    221.22,
    13.21,
    31.21,
    34.13
    
]

In [27]:
patient1 = np.array([patient1])
patient1

array([[ 17.99,  20.11,  23.11,  31.  ,  32.  , 213.43,  56.33, 234.11,
        331.31,  21.22,  11.21,  32.21,  43.21, 112.21,  33.11,  53.32,
        311.11,  89.12,  11.33, 312.12,  89.11,  97.21,  76.11,  12.11,
         91.11,  29.21, 221.22,  13.21,  31.21,  34.13]])

In [29]:
pred = Classifier.predict(patient1)
if (pred==0):
    print("Patient has no cancer")
else:
    print("Patient has cancer")

Patient has no cancer
